// ... existing code ...
    // News entity'sine uygun bir nesne oluşturun
    const newsEntity = this.newsRepository.create(news);
    return this.newsRepository.save(newsEntity);
// ... existing code ... 